### ISSUE TITLE
Question: what is the reason for using GSON in DefaultInvocationSerializer?

### ISSUE THREAD

**Issue by kzkvv** [gruelbox/transaction-outbox#236]
Hello,
Why GSON is used in DefaultInvocationSerializer? I understand this component can be overridden and I'm planning to rewrite it using Jackson for my spring boot app.
But you did choose GSON there is some reason I think, could you tell about this, please?

Btw about my problem with GSON:
I must define all classes which can be de/serialized - it's not a good solution when you have a lot of classes. In my case it's over 100 classes and this list is not final. We can have and update this list with classes, but it's weird. We don't need it with Jackson.
All my classes extends one and I got all needed classes using reflection. In my case it's not a big problem.

**Comment by badgerwithagun** [comment]
This isn't a GSON/Jackson problem.  I picked GSON because it's small and less likely to clash in classpaths with Jackson, but both libraries have the same fundamental problem.  [This article](https://snyk.io/blog/java-json-deserialization-problems-jackson-objectmapper/) describes the general issue, which is really one of security.

Let's say you have a method you're remoting with this sort of signature:

```
void callMe(int i, Collection<Animal> animals);
```
And you call it like this:
```
outbox.schedule(Service.class).callMe(1, List.of(Dog.named("Ben"))
```
Now let's say we serialize the argument list for the method like this lovely easy-to-read JSON:
```
[
  1,
  [ { "name": "Ben" ​} ]
]
```
So far so good.  The problem comes when we try and deserialize it.  We know that `1` is an integer from the target `callMe` method (we can get the parameter type from reflection).  So that's fine.  However, all we can get for the second parameter is that it's a `Collection` of `Animal`.  We _don't_ know that it's a `java.util.ImmutableCollections$List`.  It could just as easily be an `ArrayList`, or a `HashSet`, or any other collection.  The contents we know are `Animal`s, but how are we supposed to know that the member is a `Dog`?

So, we have no idea what actual implementation class is, so we can't instantiate it at runtime.  That means the JSON needs some sort of type information embedded in it in order for us to actually recreate the source data.  Unfortunately that's when things get really difficult, because JSON really doesn't make this easy. We might end up with something like this:
```
{
  "type": "Ljava.util.Object",
  "content": [
    { "type": "int", "content": 1},
    { "type": "java.util.ImmutableCollections$List", "content": [
      { "type": "my.package.Dog", "content": {  "type": "java.util.String", "content": "Ben" } }
    ]
  ]
}
```
There are various different ways of doing this and you can take some shortcuts, but you get the idea.

The above is sort of fine (in fact we do something like this in my organisation, and are likely to add it here as a PR soon) but it is a potentially serious security hole.  If someone had access to the JSON at rest, they could modify one of the classnames in the JSON to force the classloader to load a class of their choosing at runtime, potentially surfacing known vulnerabilities.

This is called a "deserialization of untrusted data" vulnerability and it's been the subject of a huge number of Jackson CVEs.  To be completely safe against it, your serialized JSON should also be encrypted or signed with a second factor so that if an attacker gained access to the database they wouldn't be able to manipulate it.

Generally, it's not a good idea to build serious vulnerabilities into your project, so I took the approach instead, with the default serializer implementation, of forcing you to specify in advance the types that you consider "safe" to deserialize, which means that even untrusted JSON can be deserialized safely. 

As you've spotted, there's nothing to stop you creating a custom serializer, but as I note above, you might want to wait.  it's a lot harder than it sounds and we already have a working version we're intending to put up here as a PR so it's available for anyone to use.
