### ISSUE TITLE
Instant Null Serialization Bug

### ISSUE THREAD

**Issue by rhobolic** [gruelbox/transaction-outbox#368]
Problem:
We are using an Instant as temporal. When it comes to com.gruelbox.transactionoutbox.DefaultInvocationSerializer.InstantTypeAdapter a NullPointerException is thrown.
![image](https://user-images.githubusercontent.com/99953472/208112999-e8854ed4-be98-4840-b1c1-aec5d9bd0b14.png)

Expectation:
The NullPointerException is not thrown

**Comment by badgerwithagun** [comment]
Thanks for this! Will take a look

**Comment by hashpyrit** [comment]
I'm having the same problem.  The object I'm serializing has an Instant field and sometimes that field has a value of null.  I'm thinking the problem is here https://github.com/gruelbox/transaction-outbox/blob/master/transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/DefaultInvocationSerializer.java#L362
There is no null check before trying to use the DateTimeFormatter.  Either that or even before we get to that line we do a null check earlier in the code.

**Comment by badgerwithagun** [comment]
I think this might be an issue with an old version of Gson - it was fixed here: https://github.com/google/gson/pull/1555

The version concerned has been a dependency of this library since February 2023, so it's likely that an older version is being pulled in somewhere else in your applications @rhobolic and @hashpyrit.

I've just tested it with the latest version in `master` and all is well.

I'm going to push the tests I've written anyway was they seem sensible to have.
