### ISSUE TITLE
transactionoutbox-spring depends on specific Spring version

### ISSUE THREAD

**Issue by tsg21** [gruelbox/transaction-outbox#44]
At the moment, it depends on Spring 5.2.6, but there's no guarantee that this will be the version that is run by the consumer.

Shouldn't the spring dependency (and others like it) be set to `<scope>provided/<scope>`?

Docs: [Dependency Scopes](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scopel)

That way the testing will be done against a specific version, but it's pulled in by consumers of the lib, and it's not transitive.

This then behaves a little like an npm "peer dependency".

Or is there a better way to achieve this that I am not aware of?

**Comment by badgerwithagun** [comment]
Maven uses a [nearest wins](http://techidiocy.com/maven-dependency-version-conflict-problem-and-resolution/#:~:text=Maven%20way%20of%20resolving%20dependency,and%20ignore%20the%20other%20versions.) policy so any conflicts will be resolved with the version your project us using.

Gradle uses a number of strategies but seems to coalesce on [highest wins](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:version-conflict).

So... not sure if it's that much of an issue unless your app is on gradle and you're stubbornly on an older version of Spring (which admittedly feels like the kind of situation where you'd really rather your peer libraries aren't making your life any harder than it already is...). Even then you can override the transitive dependency.

That said, if we're pulling in `spring-context` only for the annotations, that implies it's not needed at runtime unless the app at large knows about it already, so that can probably be `provided`.

I'd be happy to make a call on `spring-core` and `spring-tx`.  Feel free to raise a PR.
